version: '3'

services:

  workflow-editor-datastore:
    image: mongo:3.0.2
    ports:
      - "27017:27017"
    networks:
      - database

  editor:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - workflow-editor-datastore
    volumes:
      - .:/src
    networks:
      - database

networks:
  database: